// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetapp;

#nullable disable

namespace aspnetapp.Migrations
{
    [DbContext(typeof(GuardersContext))]
    partial class GuardersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("aspnetapp.EF.Guarder", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("GuarderType")
                        .HasColumnType("int");

                    b.Property<int?>("GuarderKakera")
                        .HasColumnType("int");

                    b.Property<short?>("GuarderLevel")
                        .HasColumnType("smallint");

                    b.HasKey("UserId", "GuarderType");

                    b.ToTable("Guarders");
                });

            modelBuilder.Entity("aspnetapp.EF.TreasureBox", b =>
                {
                    b.Property<string>("TreasureBoxId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TreasureBoxType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("TreasureBoxId");

                    b.HasIndex("UserId");

                    b.ToTable("TreasureBoxs");
                });

            modelBuilder.Entity("aspnetapp.EF.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<short?>("UserAP")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UserCreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UserGold")
                        .HasColumnType("bigint");

                    b.Property<short?>("UserLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserXP")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("QuestionID")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("QuestionBestTime")
                        .HasColumnType("int");

                    b.Property<short?>("QuestionStar")
                        .HasColumnType("smallint");

                    b.HasKey("UserId", "QuestionID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("aspnetapp.EF.Guarder", b =>
                {
                    b.HasOne("aspnetapp.EF.User", "User")
                        .WithMany("Guarders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("aspnetapp.EF.TreasureBox", b =>
                {
                    b.HasOne("aspnetapp.EF.User", "User")
                        .WithMany("TreasureBoxs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.HasOne("aspnetapp.EF.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("aspnetapp.EF.User", b =>
                {
                    b.Navigation("Guarders");

                    b.Navigation("Questions");

                    b.Navigation("TreasureBoxs");
                });
#pragma warning restore 612, 618
        }
    }
}
